name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, symchronize, reopened]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.platform}}
    env:
      DBGSYNCLOG: trace
      DBGSYNCON: true
    steps:
    - name: Set up Go ^1.19
      uses: actions/setup-go@v2
      with:
        go-version: ^1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    - name: Tidy
      run: go mod tidy && [ -z "$(git status -s)" ]

    - name: Lint
      run: make lint

    - name: Vet
      run: make vet

    - name: Test without coverage
      if: matrix.platform == 'macos-latest' || matrix.platform == 'windows-latest'
      run: go test ./...

    - name: Test with coverage
      if: matrix.platform == 'ubuntu-latest'
      run: go test -json -covermode=count -coverprofile=profile.cov ./... > report.json

    - name: Save PR number to file
      if: github.event_name == 'pull_request' && matrix.platform == 'ubuntu-latest'
      run: echo ${{ github.event.number }} > PR_NUMBER.txt

    - name: Archive PR number
      if: github.event_name == 'pull_request' && matrix.platform == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: PR_NUMBER
        path: PR_NUMBER.txt
       
  # notifies that all test jobs are finished.
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true