name: Go lint

on:
  pull_request_target:
    branches: [ main ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go ^1.19
      uses: actions/setup-go@v2
      with:
        go-version: ^1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Tidy
      run: go mod tidy && [ -z "$(git status -s)" ]

    - name: Lint
      run: make lint

    - name: Vet
      run: make vet