name: Go lint

on:
  push:
    branches: [ main ]

  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Set up Go 1.21
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"

    - name: Lint
      run: make lint

    - name: Vet
      run: make vet
