name: Go test

on:
  workflow_run: 
    workflows:
      [ "Permission" ]

jobs:
  test:
    strategy:
      matrix:
        platform: [macos-latest, windows-latest]
    runs-on: ${{matrix.platform}}
    env:
      DBGSYNCLOG: trace
      DBGSYNCON: true
    steps:
    - name: Set up Go ^1.19
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
      
    - name: Test without coverage
      run: go test ./...

  test_and_coverage:
    runs-on: ubuntu-latest
    env:
      DBGSYNCLOG: trace
      DBGSYNCON: true
    steps:
    - name: Set up Go ^1.19
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
      
    - name: Test with coverage
      run: go test -json -covermode=count -coverprofile=profile.cov ./... > report.json

    - name: SonarCloud scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=dedis
          -Dsonar.projectKey=dedis_debugtools
          -Dsonar.go.tests.reportPaths=report.json
          -Dsonar.go.coverage.reportPaths=profile.cov
          -Dsonar.pullrequest.key=${{ github.event.number }}
          -Dsonar.pullrequest.branch=${{ github.head_ref }}
          -Dsonar.pullrequest.base=${{ github.event.pull_request.base }}

    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
        parallel: true
        
  # notifies that all test jobs are finished.
  finish:
    needs: test_and_coverage
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
