name: Permission

on:
  push:
    branches: [ main ]
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]

jobs:
  permission:
    runs-on: ubuntu-latest
    steps:
    - name: Add comment if PR permission failed
      if: ${{ !contains(github.event.pull_request.labels.*.name, 'safe PR') }}
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🔒 Could not start CI tests due to missing *safe PR* label. Please contact a DEDIS maintainer.'
          })
    - name: Check permission
      if: ${{ !contains(github.event.pull_request.labels.*.name, 'safe PR') }}
      run: |
        echo "::error:: Could not start CI tests due to missing *safe PR* label."
        exit 1
    
