name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, symchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go ^1.19
      uses: actions/setup-go@v2
      with:
        go-version: ^1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Tidy
      run: go mod tidy && [ -z "$(git status -s)" ]

    - name: Lint
      run: make lint

    - name: Vet
      run: make vet

    - name: Sonarcloud scan
      if: matrix.platform == 'ubuntu-latest'
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.organization=dedis
          -Dsonar.projectKey=debugsync
          -Dsonar.go.tests.reportPaths=report.json
          -Dsonar.go.coverage.reportPaths=profile.cov
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Send coverage
      if: matrix.platform == 'ubuntu-latest'
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
        parallel: true      